# Generated by Django 5.2.1 on 2025-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_client_remove_user_is_therapist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('THERAPIST', 'Therapist'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20, verbose_name='role'),
        ),
    ]
