# Generated by Django 4.2.23 on 2025-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("therapist", "Therapist"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
